name: release.yml
on:
    push:
        tags:
            - 'paint*-v*'
            - '*game*-v*'
    workflow_dispatch:

run-name: '${{ github.actor }} triggered build pipeline by pushing the tag:${{ github.ref_name }}'

jobs:
    build:
        if: contains(github.ref_name, 'game') || contains(github.ref_name, 'paint')
        runs-on: ubuntu-latest
        steps:
            - name: Checking out files to runner
              uses: actions/checkout@v6
            - name: Setup node environment
              uses: actions/setup-node@v6
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Upload artifact
              uses: actions/upload-artifact@v6
              with:
                  name: 'pages-artifact'
                  path: './dist'

    deploy:
        needs: build
        if: contains(github.ref_name, 'game') || contains(github.ref_name, 'paint')
        runs-on: ubuntu-latest
        permissions:
            contents: write
        env:
            TARGET_DIR: ${{ contains(github.ref_name,'paint') && 'paint-app' || 'main-game' }}
        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v5
              with:
                  name: 'pages-artifact'
                  path: './dist'
            - name: Deploy app
              uses: peaceiris/actions-gh-pages@v4.0.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: './dist'
                  destination_dir: ${{ env.TARGET_DIR }}
                  keep_files: 'true'
